module.exports = {
  "announcements": "Announcements",
  "new_ticket": "New ticket",
  "new_email": "New email",
  "new_contact": "New contact",
  "new_company": "New company",
  "live_translate": "Live Translate",
  "customer_portal": "Go to customer portal",
  "sign_out": "Sign out",
  "keyboard_shortcuts": "Keyboard shortcuts",
  "view_shortcuts": "view shortcuts",
  "press": "press",
  "to": "To",
  "profile_settings": "Profile settings",
  "keyboard_shortcut_title": "Keyboard shortcuts",
  "learn_more": "Learn more",
  "navigation": "Navigation",
  "dashboard": "Dashboard",
  "team_inbox": "Team Inbox",
  "contacts": "Contacts",
  "solutions": "Solutions",
  "bots": "Bots",
  "analytic": "Reports",
  "campaigns": "Campaigns",
  "admin": "Admin",
  "inboxShortcuts": "Inbox shortcuts",
  "resolve": "Resolve",
  "sendAndResolve": "Send and resolve",
  "nextConversation": "Next conversation",
  "prevConversation": "Previous conversation",
  "intelliassign": "Intelliassign on/off",
  "toggleReplyPrivateNote": "Toggle reply/private note",
  "jumpToAnotherView": "Jump to another view",
  "agent_channel_availability_state": "Turn {{state}} {{channel}}",
  "off": "Off",
  "on": "On",
  "your_status": "Your status:",
  "active_on_channels": "Active on channel(s):",
  "success_status": "Successfully saved {{entity}}.",
  "error_status": "Saving {{entity}} failed.",
  "new": "New",
  "ticket": "Ticket",
  "chat": "Chat",
  "status": "Status",
  "mark_all_as_read": "Mark all as read",
  "notification_settings": "Notification Settings",
  "mute_browser_notifications": "Mute browser notifications",
  "notifications": "Notifications",
  "all": "All",
  "unread": "Unread",
  "earlier": "Earlier",
  "no_notifications": "No {{type}} notification",
  "loading": "Loading....."
}
